CHANGELOG.md
Cargo.lock
Cargo.toml
deploy/helm/spark-k8s-operator/crds/crds.yaml
docs/modules/spark-k8s/examples/example-history-server.yaml
rust/crd/Cargo.toml
rust/crd/src/affinity.rs
rust/crd/src/lib.rs
rust/operator-binary/src/history_controller.rs
rust/operator-binary/src/main.rs
tests/templates/kuttl/logging/04-deploy-history-server.yaml.j2
tests/templates/kuttl/pod_overrides/06-deploy-history-server.yaml.j2
tests/templates/kuttl/smoke/06-deploy-history-server.yaml.j2
tests/templates/kuttl/spark-history-server/06-deploy-history-server.yaml.j2
tests/test-definition.yaml

Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Default stackableVersion to operator version

---

CHANGELOG.md
tests/templates/kuttl/logging/04-deploy-history-server.yaml.j2
tests/templates/kuttl/pod_overrides/06-deploy-history-server.yaml.j2
tests/templates/kuttl/smoke/06-deploy-history-server.yaml.j2
tests/templates/kuttl/spark-history-server/06-deploy-history-server.yaml.j2
tests/test-definition.yaml

Fixup of #267
spark-k8s op is different here, as it requires the full image name instead of the `spec.image` struct. So we can't omit the stackableVersion here. We *could* omit it for the HistoryServer, but that does not really improve things.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Revert test changes that broke tests

---

CHANGELOG.md
deploy/config-spec/properties.yaml
deploy/helm/spark-k8s-operator/configs/properties.yaml
deploy/helm/spark-k8s-operator/crds/crds.yaml
docs/modules/spark-k8s/pages/crd-reference.adoc
docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
rust/crd/src/constants.rs
rust/crd/src/history.rs
rust/crd/src/lib.rs
rust/crd/src/s3logdir.rs
rust/operator-binary/src/history_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs
tests/templates/kuttl/smoke/10-deploy-spark-app.yaml.j2

CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/spark-k8s-operator-it-custom/100/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

JVM config overrides

---

docs/modules/spark-k8s/pages/index.adoc
docs/modules/spark-k8s/partials/supported-versions.adoc

Fixes: https://github.com/stackabletech/spark-k8s-operator/issues/224
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Update supported versions.

---

CHANGELOG.md
rust/crd/src/lib.rs
rust/crd/src/s3logdir.rs
rust/crd/src/tlscerts.rs
rust/operator-binary/src/history_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

fixes https://github.com/stackabletech/spark-k8s-operator/issues/282
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Let secret-operator handle PKCS#12 conversion

---

docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/getting_started.sh.j2

Part of pre-release checks listed [here](https://app.nuclino.com/Stackable/Engineering/Release-2311-d892cfac-d9de-4210-8d27-c0290b3441f4).
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Getting-started scripts - update spark application with config/naming changes

---

.gitignore
docs/modules/spark-k8s/pages/crd-reference.adoc

Fixes #326 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

correct crd docs to be inline with 23.11 release docs

---

tests/release.yaml
tests/templates/kuttl/delta-lake/00-patch-ns.yaml.j2
tests/templates/kuttl/iceberg/00-patch-ns.yaml.j2
tests/templates/kuttl/logging/00-patch-ns.yaml.j2
tests/templates/kuttl/pod_overrides/00-patch-ns.yaml.j2
tests/templates/kuttl/pyspark-ny-public-s3-image/00-patch-ns.yaml.j2
tests/templates/kuttl/pyspark-ny-public-s3/00-patch-ns.yaml.j2
tests/templates/kuttl/resources/00-patch-ns.yaml.j2
tests/templates/kuttl/smoke/00-patch-ns.yaml.j2
tests/templates/kuttl/spark-examples/00-patch-ns.yaml.j2
tests/templates/kuttl/spark-history-server/00-patch-ns.yaml.j2
tests/templates/kuttl/spark-ny-public-s3/00-patch-ns.yaml.j2
tests/templates/kuttl/spark-pi-private-s3/00-patch-ns.yaml.j2
tests/templates/kuttl/spark-pi-public-s3/00-patch-ns.yaml.j2
tests/test-definition.yaml

Part of https://github.com/stackabletech/issues/issues/566.
OKD:
```
--- FAIL: kuttl (2603.56s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/pyspark-ny-public-s3-image_openshift-true_spark-3.5.1_ny-tlc-report-0.1.0 (257.63s)
--- PASS: kuttl/harness/smoke_openshift-true_spark-3.5.1_s3-use-tls-true (385.79s)
--- FAIL: kuttl/harness/delta-lake_openshift-true_spark-delta-lake-3.5.1_delta-3.1.0 (344.43s)
--- PASS: kuttl/harness/logging_openshift-true_spark-3.5.1_ny-tlc-report-0.1.0 (655.56s)
--- PASS: kuttl/harness/spark-history-server_openshift-true_spark-3.5.1_s3-use-tls-true (588.73s)
--- PASS: kuttl/harness/spark-ny-public-s3_openshift-true_spark-3.5.1_s3-use-tls-true (252.34s)
--- PASS: kuttl/harness/iceberg_openshift-true_spark-3.5.1 (235.57s)
--- PASS: …
```

tests: added namespace patch for openshift tests

---

CHANGELOG.md
docs/modules/spark-k8s/pages/usage-guide/resources.adoc
rust/crd/src/lib.rs
tests/templates/kuttl/resources/10-assert.yaml.j2
tests/templates/kuttl/resources/10-deploy-spark-app.yaml.j2

fixes https://github.com/stackabletech/spark-k8s-operator/issues/363.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: allow fine-granular resource CPU settings

---

apps/README.md
docs/modules/spark-k8s/examples/example-sparkapp-image.yaml
examples/README-examples.md
examples/ny-tlc-report-image.yaml
tests/templates/kuttl/delta-lake/20-setup-minio.yaml
tests/templates/kuttl/logging/02-setup-s3.yaml
tests/templates/kuttl/pod_overrides/03-setup-minio.yaml
tests/templates/kuttl/pyspark-ny-public-s3-image/02-setup-minio.yaml
tests/templates/kuttl/pyspark-ny-public-s3-image/03-prepare-bucket.yaml.j2
tests/templates/kuttl/pyspark-ny-public-s3/02-setup-minio.yaml
tests/templates/kuttl/pyspark-ny-public-s3/03-prepare-bucket.yaml.j2
tests/templates/kuttl/smoke/03-setup-minio.yaml
tests/templates/kuttl/spark-history-server/03-setup-minio.yaml
tests/templates/kuttl/spark-ny-public-s3/02-setup-minio.yaml.j2
tests/templates/kuttl/spark-ny-public-s3/03-prepare-bucket.yaml.j2
tests/templates/kuttl/spark-pi-private-s3/03-setup-minio.yaml
tests/templates/kuttl/spark-pi-public-s3/02-setup-minio.yaml
tests/templates/kuttl/spark-pi-public-s3/03-prepare-bucket.yaml.j2
tests/test-definition.yaml

This is updating MinIO versions to newer charts and images since they now need be executable on both `amd64` and `arm64`
@adwk67 can you please check if updating versions of MinIO leads to problems on OpenShift? I would like this to be checked before we merge this :) 
Currently I run tests on our `Ampere arm64` server, I will report the status of those test. 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrading minio to latest (specific tag) for multi-architecuture

---

docs/modules/spark-k8s/partials/supported-versions.adoc
tests/templates/kuttl/iceberg/10-deploy-spark-app.yaml.j2
tests/test-definition.yaml

- switched 3.5.1 to java 17
- removed versions 3.4.1 and 3.5.0
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Adapt spark versions for 24.7 release

---

docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/getting_started.sh.j2
docs/modules/spark-k8s/examples/getting_started/install_output.txt
docs/modules/spark-k8s/examples/getting_started/install_output.txt.j2
docs/modules/spark-k8s/pages/getting_started/installation.adoc

docs(getting-started): update stackablectl op install output

---

docs/modules/spark-k8s/pages/history_server.adoc
docs/modules/spark-k8s/pages/usage.adoc

docs: remove home module from refs (stackabletech/documentation#637) / 23.1

docs: remove home module from refs (stackabletech/documentation#637) / 23.1

---

docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/resources.adoc

docs: remove home module from refs (stackabletech/documentation#637) / 23.11

docs: remove home module from refs (stackabletech/documentation#637) / 23.11

---

docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/resources.adoc

docs: remove home module from refs (stackabletech/documentation#637) / 23.7

docs: remove home module from refs (stackabletech/documentation#637) / 23.7

---

docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/resources.adoc

docs: remove home module from refs (stackabletech/documentation#637) / 24.3

docs: remove home module from refs (stackabletech/documentation#637) / 24.3

---

docs/modules/spark-k8s/pages/usage-guide/resources.adoc

docs: remove home module from refs (stackabletech/documentation#637)

docs: remove home module from refs (stackabletech/documentation#637)

---

docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/resources.adoc

docs: remove home module from refs (stackabletech/documentation#637)

docs: remove home module from refs (stackabletech/documentation#637) / 23.4

---

docs/modules/spark-k8s/pages/usage-guide/security.adoc

The `xref` was broken - this should fix it.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: fix incorrect link

---

docs/modules/spark-k8s/pages/usage-guide/logging.adoc

Fixes #428
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: example logging configuration for the history server

---

docs/modules/spark-k8s/pages/getting_started/first_steps.adoc
docs/modules/spark-k8s/pages/getting_started/index.adoc
docs/modules/spark-k8s/pages/getting_started/installation.adoc
docs/modules/spark-k8s/pages/index.adoc
docs/modules/spark-k8s/pages/reference/commandline-parameters.adoc
docs/modules/spark-k8s/pages/reference/environment-variables.adoc
docs/modules/spark-k8s/pages/usage-guide/examples.adoc
docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/listenerclass.adoc
docs/modules/spark-k8s/pages/usage-guide/logging.adoc
docs/modules/spark-k8s/pages/usage-guide/operations/applications.adoc
docs/modules/spark-k8s/pages/usage-guide/resources.adoc
docs/modules/spark-k8s/pages/usage-guide/s3.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: wording improvements, better install instructions

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/spark-k8s-operator/crds/crds.yaml
rust/crd/src/history.rs
rust/crd/src/lib.rs
rust/crd/src/s3logdir.rs
rust/crd/src/tlscerts.rs
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

Part of https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update to operator-rs 0.78.0

---

apps/docker/Dockerfile

Follow up of https://github.com/stackabletech/spark-k8s-operator/pull/474, there was an error in the path to the script, also some linter fixes that appear since changing the Dockerfile.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ci: fix path to ny_tlc_report script

---

CHANGELOG.md
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/pod_driver_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

Part of: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: invalid objects don't stop the reconciliation

---

docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/getting_started.sh.j2

Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/spark-k8s-operator/pull/495.

chore(getting_started): Replace templating instructions with make

---

rust/operator-binary/src/main.rs

Fixup of #515
Fixes 
`2025-01-25T14:55:33.797725Z ERROR stackable_operator::logging::controller: Failed to reconcile object controller.name="pod-driver.spark.stackable.tech" error=tried to
reconcile object Pod.v1./pyspark-pi-20250125145500-5ae7fc949df5a93e-driver.kuttl-test-resolved-flounder that was not found in local store`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Use correct label selector for pod-driver-controller

---

Cargo.lock
Cargo.nix
Cargo.toml

Part of <https://github.com/stackabletech/issues/issues/699>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
```[tasklist]
```
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
```[tasklist]
```

chore: Bump Rust dependencies pre-25.3.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/spark-k8s-operator/Chart.yaml
deploy/helm/spark-k8s-operator/crds/crds.yaml
docs/antora.yml
docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.3.0

---

tests/test-definition.yaml

Bumps:
- HBase 2.6.1
- HDFS 3.4.1
- ZooKeeper 3.9.3
They seemed to have been missed in https://github.com/stackabletech/docker-images/issues/964.
Companion change: https://github.com/stackabletech/spark-k8s-operator/pull/544

test: Update HBase, HDFS and ZooKeeper versions

---

tests/templates/kuttl/spark-connect/10-assert.yaml

:green_circle: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/spark-k8s-operator-it-custom/19/

fix: increase assert timeout

---

.github/workflows/dev_ny-tlc-report.yaml

Part of https://github.com/stackabletech/infrastructure/issues/142
This PR removes the workflow tasks pushing artifacts to Nexus from a workflow not covered by operator-templating
```[tasklist]
```
```[tasklist]
```

ci: Remove Nexus from workflow tasks

---

docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/getting_started.sh.j2
docs/modules/spark-k8s/pages/getting_started/first_steps.adoc
docs/modules/spark-k8s/pages/getting_started/installation.adoc
docs/templating_vars.yaml

Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Update helm install commands

---

CHANGELOG.md
tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml

Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests

test: Bump vector to 0.46.1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/config/jvm.rs
rust/operator-binary/src/connect/server.rs
rust/operator-binary/src/crd/history.rs
rust/operator-binary/src/crd/listener_ext.rs
rust/operator-binary/src/crd/logdir.rs
rust/operator-binary/src/crd/mod.rs
rust/operator-binary/src/crd/roles.rs
rust/operator-binary/src/crd/tlscerts.rs
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

Part of https://github.com/stackabletech/issues/issues/642.
Bump stackable-operator to 0.93.1 which versions common CRD structs.

chore: Bump stackable_operator to 0.93.1

---

.github/workflows/dev_ny-tlc-report.yaml
CHANGELOG.md
apps/README.md
apps/docker/Dockerfile
deploy/helm/spark-k8s-operator/templates/roles.yaml
rust/operator-binary/src/connect/server.rs
rust/operator-binary/src/crd/constants.rs
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs
tests/test-definition.yaml

Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details

chore: Remove hardcoded uid and gid

---

CHANGELOG.md
docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/operations/applications.adoc
rust/operator-binary/src/crd/constants.rs
rust/operator-binary/src/history/config/jvm.rs
rust/operator-binary/src/history/history_controller.rs

Part of: https://github.com/stackabletech/issues/issues/735

fix: re-enable the jmx exporter

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/spark-k8s-operator/crds/crds.yaml
deploy/helm/spark-k8s-operator/templates/roles.yaml
rust/operator-binary/src/connect/crd.rs
rust/operator-binary/src/connect/server.rs
rust/operator-binary/src/crd/history.rs
rust/operator-binary/src/crd/mod.rs
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/pod_driver_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

Part of <https://github.com/stackabletech/issues/issues/TRACKING_ISSUE>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.

chore: Bump Rust dependencies pre-25.7.0

---

tests/templates/kuttl/spark-connect/10-assert.yaml
tests/templates/kuttl/spark-connect/20-assert.yaml

Raise assert timout to wait a bit longer for image pulls.
Add a sleep command to increase the chance of apps being able to connect.
Successful on fresh AKS cluster:
```
--- PASS: kuttl (222.68s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/spark-connect_openshift-false_spark-connect-3.5.6_spark-connect-client-3.5.6 (220.11s)
PASS
```

tests: increase spark-connect test timeout

---

kind/minio.yaml
tests/templates/kuttl/delta-lake/20-setup-minio.yaml
tests/templates/kuttl/delta-lake/helm-bitnami-minio-values.yaml
tests/templates/kuttl/logging/02-setup-s3.yaml
tests/templates/kuttl/logging/helm-bitnami-eventlog-minio-values.yaml
tests/templates/kuttl/overrides/helm-bitnami-eventlog-minio-values.yaml.j2
tests/templates/kuttl/overrides/helm-bitnami-minio-values.yaml
tests/templates/kuttl/pyspark-ny-public-s3-image/02-setup-minio.yaml
tests/templates/kuttl/pyspark-ny-public-s3-image/helm-bitnami-minio-values.yaml
tests/templates/kuttl/pyspark-ny-public-s3/02-setup-minio.yaml
tests/templates/kuttl/pyspark-ny-public-s3/helm-bitnami-minio-values.yaml
tests/templates/kuttl/smoke/helm-bitnami-eventlog-minio-values.yaml.j2
tests/templates/kuttl/smoke/helm-bitnami-minio-values.yaml
tests/templates/kuttl/spark-connect/helm-bitnami-minio-values.yaml
tests/templates/kuttl/spark-history-server/03-setup-minio.yaml
tests/templates/kuttl/spark-history-server/helm-bitnami-eventlog-minio-values.yaml.j2
tests/templates/kuttl/spark-history-server/helm-bitnami-minio-values.yaml
tests/templates/kuttl/spark-ny-public-s3/02-setup-minio.yaml.j2
tests/templates/kuttl/spark-ny-public-s3/helm-bitnami-minio-values.yaml.j2
tests/templates/kuttl/spark-pi-private-s3/03-setup-minio.yaml
tests/templates/kuttl/spark-pi-private-s3/helm-bitnami-minio-values.yaml

Part of https://github.com/stackabletech/issues/issues/749 Quickfix
This PR updates the tests to use the bitnamilegacy repository for bitnami images. All affected tests ran successfully.
Integrationstests:
```
--- FAIL: kuttl (988.71s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/spark-pi-private-s3_openshift-false_spark-3.5.6 (177.04s)
--- FAIL: kuttl/harness/spark-pi-private-s3_openshift-false_spark-3.5.5 (988.69s)
FAIL
--- PASS: kuttl (115.43s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/spark-pi-private-s3_openshift-false_spark-3.5.5 (115.41s)
PASS
--- PASS: kuttl (505.49s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/pyspark-ny-public-s3-image_openshift-false_spark-3.5.5_ny-tlc-report-0.3.0 (131.97s)
--- PASS: …
```

chore: update tests to use bitnamilegacy

---

CHANGELOG.md
rust/operator-binary/src/connect/executor.rs

fix: spark connect image pull secrets not passed to executors

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/connect/controller.rs
rust/operator-binary/src/connect/crd.rs
rust/operator-binary/src/connect/executor.rs
rust/operator-binary/src/connect/server.rs
rust/operator-binary/src/crd/history.rs
rust/operator-binary/src/crd/logdir.rs
rust/operator-binary/src/crd/mod.rs
rust/operator-binary/src/crd/roles.rs
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/pod_driver_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

Part of https://github.com/stackabletech/issues/issues/762

chore: Update to stackable-operator 0.95.0

---

tests/templates/kuttl/delta-lake/40-assert.yaml
tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1275
```
--- FAIL: kuttl (5778.49s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/pyspark-ny-public-s3-image_openshift-false_spark-4.0.1_ny-tlc-report-0.3.0 (334.32s)
--- PASS: kuttl/harness/pyspark-ny-public-s3-image_openshift-false_spark-3.5.7_ny-tlc-report-0.3.0 (190.55s)
--- PASS: kuttl/harness/logging_openshift-false_spark-logging-3.5.7_ny-tlc-report-0.3.0 (717.72s)
--- PASS: kuttl/harness/pyspark-ny-public-s3-image_openshift-false_spark-3.5.6_ny-tlc-report-0.3.0 (247.91s)
--- PASS: kuttl/harness/spark-history-server_openshift-false_spark-4.0.1_s3-use-tls-true (317.18s)
--- PASS: kuttl/harness/spark-history-server_openshift-false_spark-4.0.1_s3-use-tls-false (352.71s)
--- PASS: …
```

chore: Bump zookeeper version for 25.11.0
