Cargo.lock
apps/ny_tlc_report.py
docs/modules/ROOT/pages/usage.adoc
examples/ny-tlc-report-external-dependencies.yaml
examples/spark-examples-s3.yaml
rust/crd/Cargo.toml
rust/crd/src/constants.rs
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/spark_k8s_controller.rs

Fixes #19 
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Refactor code and stabilize CRDs

---

CHANGELOG.md
Cargo.lock
deploy/helm/spark-k8s-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
docs/antora.yml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml

release 0.6.0

---

Cargo.lock
deploy/helm/spark-k8s-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
docs/antora.yml
docs/modules/getting_started/examples/code/getting_started.sh
docs/modules/getting_started/examples/code/getting_started.sh.j2
docs/templating_vars.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml

bump version 0.7.0-nightly

---

CHANGELOG.md
tests/kuttl-test.yaml.jinja2
tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml
tests/templates/kuttl/logging/spark-vector-aggregator-values.yaml.j2
tests/templates/kuttl/logging/test_log_aggregation.py

Upgrade vector
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade vector

---

docs/modules/spark-k8s/pages/getting_started/installation.adoc
docs/modules/spark-k8s/pages/index.adoc

Part of https://github.com/stackabletech/stackable-cockpit/pull/101

docs: Update references

---

docs/modules/spark-k8s/pages/crd-reference.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix links

---

rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/pod_driver_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

Part of https://github.com/stackabletech/operator-rs/issues/649

refactor: Use operator-rs Duration

---

rust/crd/src/lib.rs
rust/operator-binary/src/history/history_controller.rs
tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml

* Upgrade Vector to version 0.33.0 in the tests, which is provided by the Vector Helm chart version 0.26.0.
* Fix Clippy warnings
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade Vector to version 0.33.0 in the tests

---

docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/getting_started.sh.j2
docs/modules/spark-k8s/pages/getting_started/installation.adoc
docs/templating_vars.yaml

The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```

docs: Add listener-operator where missing

---

Cargo.lock
Cargo.toml
rust/crd/Cargo.toml
rust/crd/src/history.rs
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/spark_k8s_controller.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

bump: operator-rs to 0.56.1

---

Cargo.lock
Cargo.toml
deploy/helm/spark-k8s-operator/crds/crds.yaml
rust/crd/src/lib.rs
rust/crd/src/s3logdir.rs
rust/operator-binary/src/history/history_controller.rs
rust/operator-binary/src/spark_k8s_controller.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Chore: bump operator rs 0.61

---

deploy/helm/spark-k8s-operator/values.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add Stackable vendor label to default values.yaml

---

docs/modules/spark-k8s/pages/index.adoc

this is related to: https://github.com/stackabletech/documentation/issues/544
if this is fine, i want to add this tip to all operators.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Add tip about product image selection

---

docs/modules/spark-k8s/pages/usage-guide/history-server.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: fix link

---

docs/modules/spark-k8s/pages/usage-guide/examples.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(docs): remove deleted example bit

---

docs/modules/spark-k8s/pages/usage-guide/examples.adoc
docs/modules/spark-k8s/pages/usage-guide/job-dependencies.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(docs): fix a callout

---

tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml

Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Use Vector Helm chart version 0.34.0 in the logging test

---

docs/modules/spark-k8s/pages/getting_started/installation.adoc

docs: fix broken reference
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: fix broken reference

---

docs/modules/spark-k8s/pages/getting_started/installation.adoc

Part of https://github.com/stackabletech/documentation/pull/635

fix(getting-started): Correct file references

---

deploy/helm/spark-k8s-operator/templates/spark-clusterrole.yaml

See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): use same scc as olm

---

Cargo.lock
Cargo.toml

Part of https://github.com/stackabletech/issues/issues/548
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore(op-rs): version 0.74.0

---

docs/modules/spark-k8s/pages/getting_started/first_steps.adoc
docs/modules/spark-k8s/pages/getting_started/index.adoc
docs/modules/spark-k8s/pages/getting_started/installation.adoc
docs/modules/spark-k8s/pages/index.adoc
docs/modules/spark-k8s/pages/usage-guide/examples.adoc
docs/modules/spark-k8s/pages/usage-guide/history-server.adoc
docs/modules/spark-k8s/pages/usage-guide/job-dependencies.adoc
docs/modules/spark-k8s/pages/usage-guide/s3.adoc
docs/modules/spark-k8s/pages/usage-guide/security.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add descriptions

---

tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml

Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Upgrade the Vector aggregator in the logging tests

---

rust/crd/src/history.rs
rust/crd/src/roles.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: revert default secret lifetime to 1 day

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/spark-k8s-operator/Chart.yaml
docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1-rc2

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/spark-k8s-operator/Chart.yaml
docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1

---

tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml

Part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update Vector to 0.43.1 in integration tests

---

tests/templates/kuttl/overrides/06-assert.yaml

```
--- PASS: kuttl (169.65s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/overrides_openshift-false_spark-3.5.5 (169.63s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: add s3 region to assert step

---

tests/templates/kuttl/spark-connect/04-minio-users.yaml
tests/templates/kuttl/spark-connect/05-assert.yaml
tests/templates/kuttl/spark-connect/05-minio.yaml
tests/templates/kuttl/spark-connect/10-deploy-spark-connect.yaml.j2
tests/templates/kuttl/spark-connect/20-run-connect-client.yaml.j2
tests/templates/kuttl/spark-connect/helm-bitnami-minio-values.yaml

- **feat: add MinIO user secrets, deployment, and client configuration for Spark Connect**
- **connect test is now passing**
- **add s3 comments**

test: expand the spark connect test to write to S3

---

CHANGELOG.md
docs/modules/spark-k8s/partials/supported-versions.adoc
tests/test-definition.yaml

Part of: https://github.com/stackabletech/docker-images/issues/1080

chore: update versions for release 25.7.0

---

tests/templates/kuttl/logging/01-install-spark-vector-aggregator.yaml

Part of: https://github.com/stackabletech/docker-images/issues/1146

chore: bump vector chart to 0.43.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/spark-k8s-operator/Chart.yaml
deploy/helm/spark-k8s-operator/crds/crds.yaml
docs/antora.yml
docs/modules/spark-k8s/examples/getting_started/getting_started.sh
docs/modules/spark-k8s/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.7.0-rc1
